---
- name: manage stack (create, update or delete)
  cloudformation:
    stack_name: "{{ config.project_name }}-{{ config.env_label }}"
    region: "{{ item }}"
    state: "{{ stack_state }}"
    template: "{{ playbook_dir }}/cfn-template.yml"
    tags:
      project: "{{ config.project_name }}"
      environment: "{{ config.env_label }}"
      lifetime: "{{ config.stack_lifetime }}"
  with_items: "{{ config.stack_regions }}"

